import type { Metadata } from "next";
import { Inter, Josefin_Sans } from "next/font/google";
import "../Css/globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const josefinSans = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${josefinSans.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
