import React from "react";
import styles from "@/Css/page.module.css";
import GeneralForum from "./components/GeneralForum";
import TechnologyForum from "./components/TechnologyForum";
import LifestyleHobbies from "./components/LifestyleHobbies";
import ScienceNature from "./components/ScienceNature";

export const metadata = {
  title: "AForum",
  description: "A forum generated by next and sanity",
};

export default function MainPage() {
  return (
    <main className={styles.main}>
      <GeneralForum />
      <TechnologyForum />
      <LifestyleHobbies />
      <ScienceNature />
    </main>
  );
}
